spring:
  application:
    name: clinicaapi
  datasource:
    url: jdbc:postgresql://localhost:5432/clinicadb
    username: "postgres"
    password: "postgres"
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update